#build pdf from latex
all: ProblemStatement.tex IEEEtran.cls clean
	latex --output-format=pdf ProblemStatement.tex
	
	
clean:
	$(RM) ProblemStatement.pdf Problemstatement.toc ProblemStatement.log ProblemStatement.aux
