#build pdf from latex
all: ProjectRequirements.tex IEEEtran.cls 461Chartcut.jpg Shirt_Graphic.png clean
	latex --output-format=pdf ProjectRequirements.tex
	
	
clean:
	$(RM) ProjectRequirements.pdf ProjectRequirements.log ProjectRequirements.aux
